export const BUSINESS_CONSTANTS = {
  MAX_MESSAGE_LENGTH: 4000,
  MAX_CONVERSATION_TITLE_LENGTH: 100,
  MAX_FILE_SIZE_BYTES: 50 * 1024 * 1024, // 50MB
  CHUNK_SIZE_TOKENS: 512,
  CHUNK_OVERLAP_TOKENS: 64,
  DEFAULT_TOP_K: 5,
  SIMILARITY_THRESHOLD: 0.7,
  SLIDING_WINDOW_SIZE: 10,
  MAX_TOKENS_PER_CONVERSATION: 4096,
  CONFIDENCE_THRESHOLD: 0.6,
  SESSION_TTL_SECONDS: 86400, // 24h
  CONVERSATION_IDLE_TIMEOUT_MINUTES: 30,
  ALLOWED_FILE_TYPES: ['pdf', 'docx', 'xlsx', 'pptx', 'txt', 'md'],
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;
